### ISSUE TITLE
Mempool admission logic change: do admission check against unconfirmed state

### ISSUE THREAD

**Issue by pavitthrap** [stacks-network/stacks-core#2774]
Currently, the admission check for the mempool for a given transaction is executed against the anchored chain tip (not the unconfirmed tip). As a result, a transaction that has a balance that is valid based only on the unconfirmed state would be rejected with the current logic. Right now, the logic only refers to the unconfirmed state if the transaction has an unexpected nonce. 

Reference the function `will_admit_mempool_tx` in `src/chainstate/stacks/db/blocks.rs` for the current logic. 

This issue is to track whether or not doing the admission check against the unconfirmed tip is a change we want.

**Comment by zone117x** [comment]
@blockstack/ux-team can chime in, but my understanding is that if txs cannot be submitted against unconfirmed state, it renders the whole microblock work stream much less useful or interesting. 

It sounds like maybe the tx POST endpoint can default to the current behavior, but also support a query param to enable unconfirmed state?

**Comment by pavitthrap** [comment]
After thinking about it, it seems like allowing the mempool admission check to occur against unconfirmed state could be disruptive. 

Imagine the following sequence of transactions in subsequent microblocks, where user A starts off with 0 STX: 
- user B transfers some STX to user A (nonce 1500) 
- user A transfers STX to user C (nonce 23) 
- user A calls contract-example (nonce 24)  
- ...
- user A calls contract-example-2 (nonce 400)

If the following miner does not build off this stream of microblocks (and instead builds off the previous anchor block for example), then all of user A's transactions become invalid. This is because the next miner will mine transactions in nonce-order, and will thus attempt to mine the transaction with a nonce of 23 first. 

So, every time the next miner doesn't build off the previous microblock stream, there could be a pretty significant re-org if we do the mempool admission check against unconfirmed state.

**Comment by zone117x** [comment]
> So, every time the next miner doesn't build off the previous microblock stream, there could be a pretty significant re-org if we do the mempool admission check against unconfirmed state.

Yep, this has been an on going discussion with the UX team for a while, and are trying to structure the UI/UX to represent the risk/state around this.

**Comment by diwakergupta** [comment]
Based on my reading of the code (search call sites and implementation of `mine_next_microblock`), I believe that microblock transactions don't go through the same mempool admission checks as regular transactions. @lgalabru can you confirm? I started with the neon_noder miner and worked my way down the call graph.

**Comment by lgalabru** [comment]
There's only one entry point for submitting a transaction to the mempool - `POST v2/transactions`, and a transaction, depending on its anchoring mode (`AnchorBlockOnly` / `MicroblockOnly` / `Either`) will be returned as a candidate to the miner depending on wether they're assembling an anchor block or a microblock.

From a UX point of view, I personally think that if a transaction has its anchoring flag set to `MicroblockOnly` / `Either`, then  the mempool admission should be based on the unanchored state that the transaction is targeting.

**Comment by lgalabru** [comment]
> Imagine the following sequence of transactions in subsequent microblocks, where user A starts off with 0 STX:

@pavitthrap This is also the case when the chain fork, and anchored blocks are re-orgd, right? 
If we're taking this road, I think we'll have to mimic the mechanic in place today for updating the mempool when anchor blocks are re-org'd.

**Comment by lgalabru** [comment]
> So, every time the next miner doesn't build off the previous microblock stream, there could be a pretty significant re-org if we do the mempool admission check against unconfirmed state.

If the next miner does not build off the previous trail, then when the new block is broadcasted all the other nodes will simply discard their unconfirmed state, and take this new block as the canonical source of truth.
It could be perceived like a re-org from a user point of view, but from a stacks-node point of view, it's business as usual.

**Comment by pavitthrap** [comment]
> > Imagine the following sequence of transactions in subsequent microblocks, where user A starts off with 0 STX:
> 
> @pavitthrap This is also the case when the chain fork, and anchored blocks are re-orgd, right?
> If we're taking this road, I think we'll have to mimic the mechanic in place today for updating the mempool when anchor blocks are re-org'd.

Yes, it is also the case when anchored blocks are re-orgd. However, thousands of anchored blocks re-orging at once is not really going to happen, whereas orphaned microblocks could be a common occurrence (so allowing a different mempool acceptance criteria for microblocks could lead to this re-org behavior)


> From a UX point of view, I personally think that if a transaction has its anchoring flag set to MicroblockOnly / Either, then the mempool admission should be based on the unanchored state that the transaction is targeting.

What happens if the targeted unanchored state gets ignored by the next miner? It'll then be possible that that transaction will be invalid in the order the next miner applies transactions. In that case, a user would either have to wait for their now invalid transaction to get garbage collected, or do a replace by fee. Moreover, the transaction would be re-attempted by subsequent miners for as long as it's in the mempool.

**Comment by lgalabru** [comment]
> What happens if the targeted unanchored state gets ignored by the next miner?

That's what I meant by `we'll have to mimic the mechanic in place`. We would need to track in the mempool db the fact that a transaction was targeting a specific unanchored state, and revisit some SQL queries.

**Comment by jcnelson** [comment]
> So, every time the next miner doesn't build off the previous microblock stream, there could be a pretty significant re-org if we do the mempool admission check against unconfirmed state.

Think of the unconfirmed microblock stream as a hint that the sequence of transactions present in the stream will likely be confirmed in the next anchored block.  If you imagine a world where there were no microblocks, the situation still presents basically the same UX -- the user would see a set of unconfirmed transactions sitting in the mempool that must be mined in an order that is consistent with their nonce-orders and inter-account dependencies in order for the block(s) that contain(s) them to be valid.  Having an unconfirmed microblock stream serves two purposes here: it (1) front-loads the work of mining inter-dependent transactions that are otherwise not confirmed yet, and (2) it provides a network-wide hint as to which transactions will be next anchored to the Bitcoin chain.  But regarding (2), the UX must still convey that this is a *hint* about the state of an epoch that is *yet to happen*.

Keeping this in mind, it should be entirely expected that miners may choose not to confirm some or all of the unconfirmed microblocks, just as how miners in other blockchains may choose not to mine some or all of the unconfirmed transactions in their mempools.  A transaction being mined in a microblock is not "confirmed" at all -- it has less than 1 confirmations, but due to the economic incentives provided to subsequent miners, it can be said to be more "confirmed" than a transaction just sitting in the mempool, because you can see how much STX a subsequent miner would forfeit by ignoring an unconfirmed microblock's transactions.  However, it may be profitable to orphan blocks in the stream!  For example, there could be more than enough high-value `OnChainOnly` transactions available in the mempool that would make mining an anchored block with no confirmed microblock stream more profitable than mining a (smaller) anchored block that confirms a (larger) microblock stream.

> However, thousands of anchored blocks re-orging at once is not really going to happen, whereas orphaned microblocks could be a common occurrence (so allowing a different mempool acceptance criteria for microblocks could lead to this re-org behavior)

The difference between these two scenarios is the time scale over which they happen, which influences the seriousness of the downstream consequences of a transaction getting orphaned.  An unconfirmed microblock stream getting dropped is only visible to users if anchored block N+1 on the canonical chain does not confirm the stream produced by anchored block N.  The user would see the transaction's status switch from "unconfirmed" to "present in a microblock built off of N" to "unconfirmed" in the space of about 10 minutes -- basically, about the same as a Bitcoin transaction going from "unconfirmed" to "1 confirmation" back to "unconfirmed."  If Alice sends Bob a transaction in a microblock stream, Bob should still wait for that microblock stream to be sufficiently confirmed by some number of *anchored* blocks before treating it as accepted by the network.

A transaction getting bumped from the unconfirmed microblock stream is nowhere near as catastrophic to Alice and Bob as a transaction going from "unconfirmed" to "confirmed by 12 anchored blocks" back to "unconfirmed," since this would happen after both Alice and Bob believed that the transaction had been sufficiently confirmed that it would remain on the canonical chain forever (and taken subsequent actions based on this inference).

> From a UX point of view, I personally think that if a transaction has its anchoring flag set to MicroblockOnly / Either, then the mempool admission should be based on the unanchored state that the transaction is targeting.

I think this is a good idea, and would be straightforward to implement.

> What happens if the targeted unanchored state gets ignored by the next miner? It'll then be possible that that transaction will be invalid in the order the next miner applies transactions. In that case, a user would either have to wait for their now invalid transaction to get garbage collected, or do a replace by fee. Moreover, the transaction would be re-attempted by subsequent miners for as long as it's in the mempool.

This should be little different than a transaction in the mempool getting passed over by one or more miners.  The only way for a transaction to become invalid in given fork after it was sent is if the account that sent it got a conflicting transaction accepted into the same fork.  If Alice sends transaction T1 with nonce N, and T1 becomes invalid in fork F, then the network must have mined some other transaction T2 from Alice with nonce N in fork F.

A transaction becoming unmineable because it was sent by an account who was funded by a transaction that was never mined isn't an error, since this unmineable transaction can later become mineable.  The system doesn't care how Alice's account gets the STX needed to pay the transaction fee; it only cares that the STX are present before considering the transaction for inclusion.

A transaction's execution outcome changing from state S1 to S2 unexpectedly because the code being executed depended on state that is no longer present on the desired fork isn't an error condition either.  For example, if Alice sent a BNS name-transfer transaction that sent `alice.btc` to Bob, and Bob sent a name-update transaction for `alice.btc` *before* Alice's name-transfer was sufficiently confirmed, then it's entirely possible that Bob's name-update transaction gets mined and Alice's name-transfer does not (alternatively, they could get mined in the wrong order).  This isn't an error -- Bob's name-transfer could still be mined, but it could error out instead of actually carrying out the update.  Solving these kinds of problems isn't the mempool's job, since these sorts of inter-transaction dependencies are application-specific.

**Comment by markmhx** [comment]
> I personally think that if a transaction has its anchoring flag set to MicroblockOnly / Either, then the mempool admission should be based on the unanchored state that the transaction is targeting.

This admission functionality is expected by – and required for – our current wallets and explorer implementation. We’re talking a generally optimistic approach to summing the results of microblock and anchored transactions, and allowing users to interact sequentially based on microblock state.
 
However, it seems prudent that we always indicate in the UI whenever a balance or transaction is affected / involves microblocks, at least until we can see just how re-orgs occur in practice over a longer period of time.

**Comment by pavitthrap** [comment]
Thanks for your input Jude!

So the solution I'll implement is: 
- default behavior is to validate the tx against both unconfirmed state & confirmed state; admit if it is valid against either 
- provide a query parameter to constrain validation check to either confirmed state or unconfirmed state.

Just a side note, I have a question about this following statement: 
> For example, there could be more than enough high-value OnChainOnly transactions available in the mempool that would make mining an anchored block with no confirmed microblock stream more profitable than mining a (smaller) anchored block that confirms a (larger) microblock stream.
A leader gets 60% of the fees of the previous leader's tx fees, so how is it more profitable to put the high-value tx's in an anchor block? I get that the data a leader can send during its epoch is capped, but isn't a leader's epoch the anchored block it assembles and the trailing microblock stream?

**Comment by jcnelson** [comment]
> A leader gets 60% of the fees of the previous leader's tx fees, so how is it more profitable to put the high-value tx's in an anchor block? I get that the data a leader can send during its epoch is capped, but isn't a leader's epoch the anchored block it assembles and the trailing microblock stream?

Miner N's epoch is the microblock stream it confirms, followed by the anchored block.  The microblock stream tail it produces is part of miner N+1's epoch.

Suppose that miner N+1 has the option to confirm a microblock stream with 10 transactions worth 1 STX each, but such that each transaction takes 10% of the compute budget.  If miner N+1 confirms this stream, then they cannot mine any anchored block transactions -- their anchored block will only contain the coinbase transaction (which costs nothing), and will confirm the 10 microblock transactions for a total of 6 STX.

Suppose also that the mempool has 10 `OnChainOnly`-mode transactions worth 1 STX each, and which also each take 10% of the compute budget.  If miner N+1 builds an anchored block with these 10 transactions, and confirms zero microblocks from miner N, then miner N+1 gets a total of 10 STX.  Miner N+1 cannot confirm any microblock transactions here, because all of its compute budget is consumed by the (more profitable) anchored block transactions it mined.

Why have microblocks at all, then, if users can offer a miner more STX via the `OnChainOnly` anchor mode?  The reason is that the system doesn't know how long it will be before the next anchored block gets mined.  The next anchored block may not even be mined in the next Bitcoin block -- for example, Bitcoin transaction fees might be too high for Stacks miners to mine regularly.  Microblocks provide a way to keep the chain alive in situations like this.  If it takes a long time to mine the next Stacks block, users would set their transaction anchor modes to `OffChainOnly` to force them to be mined in microblocks (and thus show up sooner).

**Comment by pavitthrap** [comment]
Discussed this issue in the 9/17 blockchain architecture meeting. 

The UX reason behind this PR is to allow users to submit chained transactions, and have them execute in a chain of microblocks (so essentially, to be less limited by the tx chaining limit of 25). The way the linked PR (#2787) achieves this goal is by modifying the mempool admission criteria for the `v2/transactions` endpoint - instead of validating the tx against the confirmed state, we validate the tx against the unconfirmed state (which includes all the state changes induced by the microblock tip). 

Today, we were discussing limitations with the mempool, specifically that it sometimes takes a long time for tx's to propagate to other nodes in the network (and in some cases it never propagates). Discussion related to this problem is here: #2193 . 

This problem directly relates to this issue. Let's say we have a miner (node A) actively creating microblocks. This miner will actively propagate microblocks to its neighbors, which will then be able to refresh their unconfirmed state. Let's say there is some node C where it takes longer for those microblocks (and corresponding state changes) to appear. If a user were to submit their desired transaction to node A or to a node that is able to sync quickly with node A, they could achieve their desired tx chaining behavior in microblocks. However, imagine they instead pinged node C - node C could reject the transaction because its unconfirmed state might not be up to date. 

I see two potential problems that emerge from the above scenario: 
1) Users could see different behavior wrt transactions executing in microblocks depending on which node their `v2/transactions` query hits (since the unconfirmed state might be behind the miner's unconfirmed state, so different transactions will appear valid to different nodes). 
2) Since there will be different mempool acceptance criteria (with the proposed change in this issue) that results from variance in the unconfirmed state, the problem of the propagation of transactions across nodes will only be exacerbated. A node that rejects a transaction from other nodes as invalid since its unconfirmed state is behind won't have a chance of re-obtaining that tx later (unless a manual script is used, like the mempool pusher daemon). 

Due to (2), we don't think we should release this change before there is better transaction propagation between mempools. 

Also, would welcome discussion about (1) in general. I'm wondering how big of an issue this could be (maybe it won't be, because microblocks are propagated quickly enough/ the mempool is better able to re-propagate txs).

**Comment by markmhx** [comment]
> A node that rejects a transaction from other nodes as invalid since its unconfirmed state is behind won't have a chance of re-obtaining that tx later (unless a manual script is used, like the mempool pusher daemon).

Could nodes automatically keep transactions on hand that they've rejected recently because of such state issues, and recheck them as more transactions arrive in their mempools, to see if they are actually valid in relation to those arriving transactions?

Perhaps the initial rejection could be communicated in a way (e.g. particular status code) that lets clients know the nature of the _preliminary_ rejection. They could then choose to display them as pending or similar until rejected more permanently.

**Comment by pavitthrap** [comment]
> Could nodes automatically keep transactions on hand that they've rejected recently because of such state issues, and recheck them as more transactions arrive in their mempools, to see if they are actually valid in relation to those arriving transactions?

I think if we kept invalid tx's on hand to retry that could be a DoS vector? Someone could send a node a stream of invalid tx's, all of which the node would keep hold of. That could lead to (1) memory issues, and (2) could busy the node up, bc it would need to try re-check tx's in some sort of systematic way (for example, with exponential backoff). I could be wrong about this, but it seems unfeasible to me. 

In order to feel comfortable releasing this feature, I think we want to have a better propagation protocol in place for both transactions & microblocks. However, I think userx related testing for this feature can occur now.

**Comment by markmhx** [comment]
> I think userx related testing for this feature can occur now.

We could start testing now since you're confident we'll find a better propagation protocol soon in any case? 

We're not in a particular rush on the UserX side to test this, so perhaps we should wait until we have a complete solution for this admission check change before moving on to that stage. I appreciate the idea though. 🙏

**Comment by diwakergupta** [comment]
This is still incomplete, right @pavitthrap ?

**Comment by markmhx** [comment]
I'd certainly love to see this initiative pushed forward in the hopes that we can improve the UX around microblocks in general.

**Comment by jcnelson** [comment]
This is no longer relevant because microblocks have been disabled
