### ISSUE TITLE
Nakamoto: Implement the stacker signature / set validation in the Sortition DB

### ISSUE THREAD

**Issue by kantai** [stacks-network/stacks-core#3927]
In the Neon milestone, the stacks blockchain operates with a
*single* stacker-signer.  This means that the `TenureChange`
operation and all `NakamotoStacksBlock`s must be signed by this
single signer. This should be implemented through a mocked
endpoint on the SortitionDB:

`validate_signer(message: &[u8], signature: &MessageSignature) -> Result<bool>`

**Comment by saralab** [comment]
Update based on the deep dive from Aaron: 
- Instead of mocking the set of stackers in the sortition DB , implement the stacker signature / set validation in the Sortition DB. This will be a Schnorr signature TransactionAuth variant.

**Comment by jcnelson** [comment]
Adding a key finding that @jferrant and I discovered.

The call to `NakamotoChainState::accept_block()` needs to ultimately pull out the block's parent's view of the aggregate public key in `pox-4`.  That is, the aggregate public key is _not_ stored in the sortition DB at all; it's _only_ stored in the `pox-4` data space.  This is because:
   1. DKG can complete at any time; it's not guaranteed to happen on a reward cycle boundary or a tenure boundary
   2. DKG can happen multiple times per reward cycle in order to add more signers (see https://github.com/stacks-network/stacks-core/issues/4059#issuecomment-1815385129)

**Comment by kantai** [comment]
> DKG can happen multiple times per reward cycle in order to add more signers (see https://github.com/stacks-network/stacks-core/issues/4059#issuecomment-1815385129)
> DKG can even happen multiple times per tenure

I think this merits more careful consideration -- allowing DKG to happen multiple times per cycle adds some non-trivial complexity to the system. I agree that supporting stacker key-change would allow the system to tolerate more failure scenarios, but I would strongly suggest that this be delayed past neon at least. Instead, the DKG result should be queried like the reward set is today: at the first bitcoin block of the new reward cycle, the aggregate public key should be available.

**Comment by jcnelson** [comment]
Opened an issue for that here: https://github.com/stacks-network/stacks-core/issues/4107
