### ISSUE TITLE
[stacks-signer] All signers should calculate the DKG key simulateously 

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#3972]
To prevent malicious actors, we should have all signers publish the result of the DKG round. This means we need to update stacks-signer code to have every signer run DKG simultaneously. A single coordinator should still trigger the round, but every signer should aggregate the results.

**Comment by jferrant** [comment]
1. https://github.com/stacks-network/sbtc/issues/392
2. https://github.com/stacks-network/sbtc/issues/393
3. https://github.com/stacks-network/sbtc/issues/394 Depends on 1 and 2

**Comment by jcnelson** [comment]
Task breakdown
- need to have a way to pick a coordinator, in order to start the protocol or resume from a coordinator crash
   - need to deal with network partitions / dueling coordinators
- need to replicate coordinator state to all nodes so they can monitor the coordinator's behavior
   - need to locally decide to ignore faulty (equivocating) or fail-slow/fail-stop coordinators
   - need to be able to detect and resume/restart DKG from a failed coordinator
   - nodes need to individually vote that nodes are faulty (66% threshold required to overcome Byzantine voters)
- need to individually vote for aggregate public key, taproot address, and tapscripts via `.pox-4`

N.B. DKG requires 100% participation from all signers -- all of them must complete their DKG steps.  Whoever completes DKG becomes the set of signers for the reward cycle (meaning, the more signers that must be kicked out, the lower our margin of error for clearing the 70% signing threshold)
