### ISSUE TITLE
stacks-node must write the new set of stackers to the .pox-4 contract

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#3980]
At T-99 block, Miner must write the new reward cycle set of signers and reward shares to the pox-4 contract.
The clarity stacker-db contract requires this information to update the config with the appropriate stacker addresses

Depends on https://github.com/stacks-network/stacks-blockchain/issues/3970
Related to (Duplicates?): https://github.com/stacks-network/stacks-core/issues/4058

**Comment by jcnelson** [comment]
Context: once the PoX anchor block is chosen in Nakamoto (something that we'll know 99 blocks prior to the start of the next reward cycle), the node will need to (a) calculate the reward set right then and there, and (b) write this information into `.pox-4` somehow _in addition_ to into the sortition DB as it does today.  This is because the StackerDB trait implementation for `.pox-4` needs to know the addresses and number of slots for the next set of Stackers _before_ the next reward cycle begins (i.e. so the new Stackers can do DKG and vote on the next reward cycle's aggregate public key).

**Comment by jcnelson** [comment]
The reward set is calculated in the first prepare-phase block, so the Stacks node will simply call into `.pox-4` to write the new signing key addresses to the StackerDB configuration for the new signers.  This would be part of the consensus rules, via `setup_block()` or some such.

**Comment by setzeus** [comment]
Pasting design doc that mentions this issue for reference: https://docs.google.com/document/d/1IFTaHjEGHJkdFiEfKNayfmD0UlseoXpVcoMgJv0VW1g/edit?usp=sharing

**Comment by MarvinJanssen** [comment]
This was addressed in #4263 and #4269. Signer sets are now written to a dedicated boot contact `.signers` instead of the PoX-4 contract.
