### ISSUE TITLE
Nakamoto: Implement a neon genesis block generation routine

### ISSUE THREAD

**Issue by saralab** [stacks-network/stacks-core#4028]
In Neon operation, a single miner produces nakamoto blocks using bitcoin regtest. This single miner _does not_ communicate with stackers in order to obtain valid TenureChange transactions. Instead, the neon miner produces and signs `TenureChange` transactions by themselves. In order for those transactions to validate, the miner's public key must be the PoX-4 contract's active aggregate public key.

In order to do this, during the "genesis" block of the neon miner, the pox-4 contract should be explicitly instantiated with the aggregate public key.

The neon node initiates the chainstate and executes genesis instructions here:

https://github.com/stacks-network/stacks-core/blob/feat/nakamoto-coordinator/testnet/stacks-node/src/run_loop/neon.rs#L444

**Comment by saralab** [comment]
@kantai : Can you add more details to implement here based on our current conversation?

**Comment by jferrant** [comment]
> @kantai : Can you add more details to implement here based on our current conversation?

Before I get super deep into this, this requires modification to boot_chainstate to include an explicit setting of the aggregate public key to the miner's key so it can sign and validate transactions as a temporary hold over before signers set their own dkg key?

**Comment by kantai** [comment]
I edited the issue to add more context above.

> Before I get super deep into this, this requires modification to boot_chainstate to include an explicit setting of the aggregate public key to the miner's key so it can sign and validate transactions as a temporary hold over for neon specifically. Just want to make sure I am understanding this.

Yep, that's exactly the idea.

I'm not 100% positive that this is a viable strategy, though, because the pox-4 contract doesn't _exist_ at genesis, so we may have to do something else.

In my mockamoto PR (opening soon), I just ensure that the miner has enough STX to dominate the stacking pool, and configure it to continuous issue `stack-stx` invocations. This isn't the most elegant, but it works, and that maybe the approach that's necessary in neon as well.

**Comment by OSTO79** [comment]
All right I can't take it I can't take it anymore I am clueless about what
the fuck is even going on because I was in prison for 10 years kind of lost
track of what the fuck is really going on so can somebody bring me up to
speed so we can just get this fucking over with I mean I'm broken homeless
here
