### ISSUE TITLE
[stacks-core] Update .pox-4 to calculate signer key vote shares

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#4059]
Given the map of signer-key (public key) to an amount of stacked stx, calculate the number of vote shares allocated to that signer. Note that the vote power should be capped at 25% and the remaining percentage normalized over the other signers.

**Comment by kantai** [comment]
Something related to this that occurs to me is the consequences of participation in the DKG process. The DKG process _cannot_ require 100% participation. Otherwise, someone qualifying for a single stacker slot could simply stall the process.

If the DKG has 100% participation, then the threshold for signing should be 70%, and the vote threshold should be 100% -- _not_ 70%. Because otherwise, a 70% group could construct an aggregate key including only shares for themselves, and then successfully elect that aggregate key.

If the DKG has _less_ than 100% participation, then the threshold for signing must be higher (i.e, if only 70% of stackers participate in DKG, then the threshold signature must be 100%), and the voting process must enforce this.

**Comment by kantai** [comment]
Tagging @jcnelson @xoloki for some more thoughts on the above.

**Comment by jcnelson** [comment]
I don't think there was ever a world where the system could only work with 100% Stacker participation in DKG.  It needs a way to operate in a degraded mode of operation when less than 100% of Stackers are online.

However, I also believe that there is no world in which the system allows blocks to be produced with fewer than 70% of the locked STX signing them.  So, that leaves us in a position where if fewer than 100% Stackers participate in DKG, then a greater fraction of the participating Stackers will need to participate in signing rounds so that the absolute 70% minimum is cleared.

A naive solution of running DKG once per reward cycle and just doing our best afterwards could put us in a precarious position where there's essentially no room for signers to drop off.  For example, suppose only 71% of the Stackers (by stacked STX) participated in DKG -- then, >99% of these Stackers would be required to sign blocks, and the remaining 29% of Stackers don't have anything to do.

So, I'd propose two mitigations:

* **Allow DKG to happen at any point in the reward cycle.**  but such that the number of stacked STX the aggregate public key represents can only increase.  Then, the implementation begin the reward cycle with a smaller-than-desired number of Stackers signing blocks, but signers could re-request DKG until enough Stackers have participated (e.g. over 95%).

* **Disable PoX rewards for non-participating Stackers.**  We'd track which Stackers participate in DKG, and which ones do not.  Stackers that do not participate in DKG -- i.e. their private key shares are not represented by the aggregate public key -- would receive no PoX rewards.  This would incentivize them to re-request DKG until they can be included.  To achieve this, a Stacker would run a signing round on the hash of their public key and post the aggregate signature along with their vote for the aggregate public key.  Other signers wouldn't sign this hash if the requesting signer didn't participate in DKG, which would deny them a valid vote (i.e. it prevents a freerider Stacker from just re-submitting an aggregate public key vote that it got from the blockchain).

**Comment by setzeus** [comment]
Double-checking my understanding here the source of truth for the "vote-round" will live in agg-pubkey? Any reason key for agg-pubkey isn't an optional- shouldn't it be "none" until a key > 70% consensus?

**Comment by setzeus** [comment]
Pasting design doc that mentions this issue for reference: https://docs.google.com/document/d/1IFTaHjEGHJkdFiEfKNayfmD0UlseoXpVcoMgJv0VW1g/edit?usp=sharing

**Comment by jcnelson** [comment]
> @setzeus Double-checking my understanding here the source of truth for the "vote-round" will live in agg-pubkey? Any reason key for agg-pubkey isn't an optional- shouldn't it be "none" until a key > 70% consensus?

Ah, this data var could have type `(optional { .. })`, since the key may not be set yet.  Also, having talked more with @jferrant about it, there will probably be two public key records -- one for the current signers, and one for the previous signers (since both sets will be active towards the end of the prepare phase).

**Comment by kantai** [comment]
@jcnelson, @xoloki, @jferrant -- is there an issue or discussion topic already for updating the signer binary to handle non-responsive stackers?

**Comment by jcnelson** [comment]
I don't think so.

**Comment by kantai** [comment]
Okay -- issue created (https://github.com/stacks-network/stacks-core/issues/4111), and I dropped some thoughts on it there.

**Comment by setzeus** [comment]
@friedger this ticket is for the Rust side / binary, yours (#4116) is for the Clarity side / smart contract.
