### ISSUE TITLE
[Nakamoto] Nakamoto block broadcast

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-core#4066]
When the miner produces a block, it must be broadcast via p2p to the rest of the network.  The broadcast strategy should ensure that most of the time, most nodes receive the block (so anti-entropy does not need to kick in).

**Comment by saralab** [comment]
Task 1: S
- Relayer does the broadcast : requires more testing , sensitive to 5s block times. Might be deleting code instead of adding it. 

Task 2: S
- Nodes that don't have the same chaintip off by few , should buffer , instead of anti-entropy state machine . We do this today. Update for Nakamoto
- Tap into existing buffering mechanism

**Comment by jcnelson** [comment]
Task 3: S

We need a Nakamoto-specific p2p blocks message so we can carry out the broadcast.

**Comment by jbencin** [comment]
@kantai @jcnelson 

Going to need some help to get started on this one too, like which parts of the code I'll need to touch

**Comment by jcnelson** [comment]
Hey, this is blocked on having Nakamoto block p2p messages, including codecs and handlers for them in the p2p stack.

**Comment by jbencin** [comment]
> Nakamoto block p2p messages, including codecs and handlers

@jcnelson is there a ticket for this? Is this something I can/should do?

**Comment by jcnelson** [comment]
@jbencin There is now: https://github.com/stacks-network/stacks-core/issues/4069.  Feel free to take a stab!
