### ISSUE TITLE
[Nakamoto] Update block anti-entropy state machine to handle Nakamoto blocks

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-core#4067]
The block anti-entropy state machine needs to be able to identify peers that are missing one or more tenures' block streams, and send them over.

**Comment by saralab** [comment]
Blocked on #4066 

- P2P message wireformat for Nakamoto blocks

**Comment by jbencin** [comment]
@jcnelson or @kantai I'll need some more detail on this in order to start, I'm not familiar with the "anti-entropy state machine" or the network code at all.

I assume something like this is already implemented for things other than Nakamoto blocks. If so, I should be able to get started if you point me towards the relevant files and functions
