### ISSUE TITLE
[stacks-signer] Make Signers use only two stacker-db slots each

### ISSUE THREAD

**Issue by jferrant** [stacks-network/stacks-core#4152]
Update stacks signer's to only utilize one stacker db slot each. This means also updating the generate files CLI command.

**Comment by xoloki** [comment]
I know this is possible, but it means that there is no ability for a signer, or anyone else, to use stackerdb to recreate state.  If we do this we might as well just pass around p2p messages.

In the current design, we have one message of every type for every signer, so we can always see the current dog and signing state for every signer.

**Comment by jcnelson** [comment]
@xoloki How big is the per-slot state? Would it all fit into a single stackerdb chunk?  Because if so, you could achieve the same end simply by appending the new DKG message to the chunk instead of overwriting it.

**Comment by xoloki** [comment]
@jcnelson dkg messages vary in size based on the total number of reward slots, threshold needed to sign, and number of slots controlled by a signer. It's doubtful you'd fit even one, much less multiple, into a single chunk in a production scenario.

**Comment by jcnelson** [comment]
@xoloki The trade-off is as follows:

* We can use stackerdb as a persistence mechanism for DKG state, but that would mean that we need three separate stackerdb instances -- one for the current signers, one for the new signers coming online at the reward cycle boundary, and one for the miners.  This is certainly doable, but the cost is that each node would need to do bookkeeping for three separate stackerdb instances.  This entails synchronizing full DB inventory messages on each StackerDB replica state-machine pass (every `write-freq` seconds as obtained by the contract), which at 20kb each would be around 60kb of data exchanged with each neighbor.  If `write-freq` is 30s, then this would amount to about 1.2mb data exchanged every 10 minutes (by contrast, a Stacks block is about 0.2-0.5mb today). 

* To cut down on the data exchanged, we can use a single stackerdb instance, which means 0.4mb exchanged every 10 minutes.  But, it would mean that we can't use stackerdb for persistence.

We can vary `write-freq` above to be longer, if benchmarking shows us that the stackerdb message broadcast code reliably gets updates sent to each replica (state-machine passes only do inventory syncs as a fall-back in case they miss a pushed message).

**Comment by jcnelson** [comment]
Summarizing a huddle we had:

* We'll keep the 10 slots per signer organizing paradigm.  This is highly desirable because it makes it straightforward for a coordinator replica to come online even if it doesn't receive all DKG-broadcasted messages. The StackerDB internals ensure eventual message delivery of all intermediate DKG messages as long as the signer's Stacks node is connected to other nodes that collectively possess a full replica of all messages.

* We'll have the `.pox-4` contract throttle up the `write-freq` value during the prepare phase (i.e. made smaller), so signers' nodes poll for missing DKG messages more frequently when DKG is running. The `write-freq` value will be throttled down during the reward phase, where this isn't as important.  This alleviates my initial concern that having multiple StackerDB replicas would potentially put bandwidth pressure on the nodes.
