### ISSUE TITLE
[Nakamoto] PoX reward set state should include the signing key, not the stacker state

### ISSUE THREAD

**Issue by jcnelson** [stacks-network/stacks-core#4274]
The PoX reward set maps need to track the signing key.

**Comment by setzeus** [comment]
Confirming that this means we should *remove* the existing field from 'stacking-state' which actually has a neat secondary effect: instead of setting the signing-key per-member using 'delegate-stack-stx' the pool operator can now provide a single signing-key w/ 'aggregate-commit-index.'

This is useful since currently a pool operator rotating signing-keys (for some grief reason) midway through stacker sign-ups would cause members already stacked w/ the old key to miss the next cycle.

**Comment by setzeus** [comment]
Discussed & assigned to WIP in #4263.

**Comment by MarvinJanssen** [comment]
This was addressed in #4263 and #4269.
