### ISSUE TITLE
Signers should include their stacks_tip_consensus_hash view in their StackerDB messages

### ISSUE THREAD

**Issue by 8marz8** [stacks-network/stacks-core#4292]
Stacks-signer uses the stacks_tip_consensus_hash to introduce randomness in selecting a coordinator (part of #4276). This issue is related to the feedback on the implications of this selection mechanism and the necessary steps to distinguish slower or divergent signers from Byzantine ones. To address this, signers should include their view of the stacks_tip_consensus_hash in StackerDB messages.

Below is a detailed specification:
https://github.com/stacks-network/stacks-core/pull/4276#discussion_r1465399027

**Comment by jferrant** [comment]
So this is what I think should be done at least for a first draft. Similar to your preliminary thoughts but with some slight variation.

So we can't use extended API endpoints unfortunately, but I think you have all the info you need via the v2/info endpoint.

What I would anticipate signers doing is every DKG or Sign message they send should be wrapped in a new message type (so instead of just SignerMessage::Packet(wsts::Packet), it would be SignerMessage::Packet(PacketInfo) where Packet info contains a wsts::Packet as well as the consensus_hash that the signer currently has for their stacks node view and potentially also their block height. Then signers who receive this message, if their view is different, they can check if its because they are outdated (i.e. is their block height behind?), verify the consensus_hash calcualtion in calculate_coordinator matches and they can use this to know "oh I have an outdated view. Overwrite the coordinator to be from this new consensus hash. However, if they see "hey you sent me an outdated conesnsus hash and block height, we will need a new NACK style message to send back. This is where you might need a new slot ID (to prevent overwriting DKG / Sign rounds that are valid) and this message would contain the consensus hash and block height so that the outdated signer can then update their view.
