### ISSUE TITLE
/v2/info only updates on burn block 

### ISSUE THREAD

**Issue by obycode** [stacks-network/stacks-core#4351]
In running the managed testnets, we realized that the /v2/info endpoint does not stay up-to-date with the current Stacks tip height. Instead it is only updating when a new burn block is processed.

**Comment by jcnelson** [comment]
Yup, that's the current design.

**Comment by jcnelson** [comment]
You can fix it by checking the canonical stacks tip instead of the burnchain tip when determining whether or not the state for /v2/info needs to be reloaded. Unfortunately I'm too behind on the network state machines to do this right this second, but if you don't feel comfortable doing it, I can fold it into one of the PRs.

**Comment by obycode** [comment]
Yup, I can take this one when I have some time.

**Comment by jcnelson** [comment]
PR sent
