### ISSUE TITLE
Update Clarunit To Include Coverage

### ISSUE THREAD

**Issue by setzeus** [stacks-network/stacks-core#4434]
**Describe the bug**
The currently-working Clarunit testing framework hosted ['stacks-test-tools'](https://github.com/stacks-network/stacks-test-tools) in & used in ['stacks-core'](https://github.com/stacks-network/stacks-core) is a sub-optimal implementation since it does not currently generate code coverage nor does it count towards the CI coverage. 

Both of these items should be fixed & added into 'stacks-core.'

**Comment by MarvinJanssen** [comment]
It does generate a coverage report. File is `contrib/core-contract-tests/lcov.info`. It probably just needs to be added to the yaml.

**Comment by MarvinJanssen** [comment]
Looks like the legend @wileyj already uploads that file to Codecov:

https://github.com/stacks-network/stacks-core/blob/021eaaeff87d6b518b037fd1e90a938177aabd4c/.github/workflows/stacks-core-tests.yml#L158C1-L165C32

We can just verify it works and if so, close the issue.

(The issue with `genhtml` is separate from this.)

**Comment by MarvinJanssen** [comment]
Looks like the upload is failing.

```
  Codecov report uploader 0.7.2
[2024-02-29T09:43:25.999Z] ['info'] => Project root located at: /home/runner/work/stacks-core/stacks-core
[2024-02-29T09:43:26.003Z] ['info'] -> No token specified or token is empty
[2024-02-29T09:43:26.012Z] ['info'] Searching for coverage files...
[2024-02-29T09:43:26.054Z] ['error'] None of the following appear to exist as files: ./lcov.info
[2024-02-29T09:43:26.054Z] ['error'] There was an error running the uploader: Error while cleaning paths. No paths matched existing files!
[2024-02-29T09:43:26.054Z] ['info'] Codecov will exit with status code 0. If you are expecting a non-zero exit code, please pass in the `-Z` flag
```

**Comment by MarvinJanssen** [comment]
Looks like I got it to work. 4962452 in #4231 made the Clarinet coverage report show up on Codecov. However, the percentage change is out of whack and it only counted direct changes to the test files. The boot contracts themselves are counted as indirect changes as can be seen here: 

<img width="1060" alt="image" src="https://github.com/stacks-network/stacks-core/assets/5727806/fa727ba3-cee5-4d85-b3e2-033120c857c1">

<img width="1052" alt="image" src="https://github.com/stacks-network/stacks-core/assets/5727806/20f11489-d09c-4f70-ad4e-1a19d805e5af">

@wileyj do you know why that is? Perhaps because the Codecov workflow was just fixed and it did not properly pick up prior commits?

**Comment by MarvinJanssen** [comment]
This was solved in the linked PR.
