### ISSUE TITLE
Current `next` branch has no way of running full scale (4k reward slot) dkg/sign tests

### ISSUE THREAD

**Issue by xoloki** [stacks-network/stacks-core#4456]
**Describe the bug**
Recent changes to the `next` branch prevent running full scale dkg/sign tests.  This means we have no idea if we can still achieve the nakamoto block signing target time of 5 seconds; the performance at the scale allowed by the current tests indicates that signing will take significantly longer at full scale.

**Steps To Reproduce**
In `next` c283311773c96ab5d7a4094f13651bd1a655ecb2 it was possible to run a full scale dkg/sign test with the following small diff:
```
diff --git a/stacks-signer/src/config.rs b/stacks-signer/src/config.rs
index d89ae603d..c8cf36ec4 100644
--- a/stacks-signer/src/config.rs
+++ b/stacks-signer/src/config.rs
@@ -38,7 +38,7 @@ use wsts::state_machine::PublicKeys;
 /// List of key_ids for each signer_id
 pub type SignerKeyIds = HashMap<u32, Vec<u32>>;
 
-const EVENT_TIMEOUT_MS: u64 = 5000;
+const EVENT_TIMEOUT_MS: u64 = 128;
 
 #[derive(thiserror::Error, Debug)]
 /// An error occurred parsing the provided configuration
diff --git a/testnet/stacks-node/src/tests/signer.rs b/testnet/stacks-node/src/tests/signer.rs
index e2cf03b24..31c800da0 100644
--- a/testnet/stacks-node/src/tests/signer.rs
+++ b/testnet/stacks-node/src/tests/signer.rs
@@ -370,7 +370,7 @@ fn stackerdb_dkg_sign() {
     let mut msg = block.header.signer_signature_hash().0.to_vec();
     msg.push(b'n');
 
-    let signer_test = SignerTest::new(10, 400);
+    let signer_test = SignerTest::new(16, 4000);
 
     info!("------------------------- Test DKG -------------------------");
     info!("signer_runloop: spawn send commands to do dkg");
@@ -384,7 +384,7 @@ fn stackerdb_dkg_sign() {
         let mut aggregate_public_key = None;
         loop {
             let results = recv
-                .recv_timeout(Duration::from_secs(30))
+                .recv_timeout(Duration::from_secs(300))
                 .expect("failed to recv dkg results");
             for result in results {
                 match result {
@@ -438,7 +438,7 @@ fn stackerdb_dkg_sign() {
         let mut schnorr_proof = None;
         loop {
             let results = recv
-                .recv_timeout(Duration::from_secs(30))
+                .recv_timeout(Duration::from_secs(300))
                 .expect("failed to recv signature results");
             for result in results {
                 match result {
@@ -462,7 +462,7 @@ fn stackerdb_dkg_sign() {
                 }
             }
             if (frost_signature.is_some() && schnorr_proof.is_some())
-                || sign_now.elapsed() > Duration::from_secs(100)
+                || sign_now.elapsed() > Duration::from_secs(300)
             {
                 break;
             }
```

This diff explicitly sets the number of reward slots/key_ids to `4000`, updates the timeouts so they don't get accidentally triggered, and lowers the command timeout for the `stacks-signer` runloop so we don't waste any time waiting for the dkg/sign commands to be handled.

With this diff, running the `stackerdb_dkg_sign` test in release mode gives a result of 
```
DKG Time Elapsed: 93.03s
Sign Time Elapsed: 10.91s
```

The sign time is actually doing two signatures: a regular `FROST` signature, and a `taproot` schnorr proof.  

In current `next`, though, it is no longer possible to explicitly set the number of reward slots, since this is now a function of the reward cycle length.  Altering the reward cycle length is possible, but there is a set of byzantine calculations that make it difficult to set this large enough to get a full scale test without taking hours, and even then it usually just hangs.

**Expected behavior**
Some way to reliably test the system at full scale without taking hours.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Rust version: rustc 1.75.0 (82e1608df 2023-12-21)

**Comment by xoloki** [comment]
I've pushed a branch with these changes:

https://github.com/stacks-network/stacks-core/tree/feat/full-scale-signer-test

**Comment by kantai** [comment]
There is not and there _should not_ be a way to end-to-end test reward cycles of incoherent size. If the reward size is 4000 slots, there must be 4000 slots during the reward cycle. There are exactly two slots per bitcoin block, because the system cannot support more burn outputs for miner commitments. This means that the reward cycle length must be 2000. Allowing reward sets that do not fit into a single reward cycle would introduce dangerous possibilities of incoherence in the system.

There are multiple options for testing this-- (1) mock the necessary interactions with the stacks-node, (2) prepare and integrate a prebuilt chainstate for the stacks-node to avoid needing to execute the first 2000 blocks of the test on every execution, (3) unit test.

The benefit of (2) is that it involves actually running a realistic scenario, and would be useful for configuring a multi-node environment, which is the kind of end-to-end test we will want to do eventually anyways.

As I suggested sometime earlier when this topic came up, this test of DKG is only interested in setting up a reward set and submitting aggregate key votes, so its not really the case that the full reward cycle needs to run with stacks blocks -- you just need to get to the first pox-4 reward cycle's prepare phase. So you could run a test that mines 2000 bitcoin blocks (which is pretty quick in regtest) and then spins up the `stacks-node` miner.
