### ISSUE TITLE
Nakamoto: vrf-seed in get-tenure-info

### ISSUE THREAD

**Issue by friedger** [stacks-network/stacks-core#4716]
Currently vrf-seed is part of `get-block-info?` This is wrong for Nakamoto as the sortition happens on tenure level. 

**Describe the solution you'd like**
Add a new function `get-tenure-info?`

**Additional context**
There are more properties that needs to be checked. See e.g. https://github.com/stacks-network/stacks-core/issues/4541#issuecomment-2077249574

**Comment by obycode** [comment]
I agree. We should probably move several of these properties to a new `get-tenure-info?`. There is a challenge because this was not included in the SIP. We'll need to figure out what is the best way to add this. If you have time to writeup a potential add-on SIP, that would probably be very helpful.

**Comment by friedger** [comment]
Here is the Addendum to SIP-21 https://github.com/stacksgov/sips/pull/178

**Comment by obycode** [comment]
This is being implemented together with #4541.
